module.exports=db=>{
    db.getTwoMenConversation=
        require('./loadChatProperties/getTwoMenConversation')
    db.getConversations=
        require('./loadChatProperties/getConversations')
    db.getMessages=
        require('./loadChatProperties/getMessages')
    db.newMessage=
        require('./loadChatProperties/newMessage')
}
