module.exports=o=>{
    o.getTwoMenConversation=
        require('./loadChatProperties/getTwoMenConversation')
    o.getConversations=
        require('./loadChatProperties/getConversations')
    o.getMessages=
        require('./loadChatProperties/getMessages')
    o.newMessage=
        require('./loadChatProperties/newMessage')
    o.userOwnConversation=
        require('./loadChatProperties/userOwnConversation')
}
